### ISSUE TITLE
phx gen should accept pipeline definitions

### ISSUE THREAD

**Issue by jbsolomon** [phoenix-engine/phx#30]
`phx gen` should read a file that defines pipeline steps and operate all of them.  For example:

```yaml
# read_all finds all files, optionally matching a given regex string.
read_all:
  files: p each p match $ p list $

# compress streams each file into a compressed buffer.
compress:
  comped: p each $ p comp -lz4 -l 9

# compile translates the given shaders into SPIR-V and then into C++ literals.
compile:
  spv: p each compress.comped p shader compile
  cpp: p each spv p gen cpp 

# diff compares the output of compile against the previous asset manifest.
diff:
  out: p manifest diff compile.cpp

# gen is the entrypoint which performs the pipeline steps.
gen:
  - read_all @matches @from
  - compress read_all.files
  - compile
  - diff
  - out @to
```
